substitutions:
  _REPO: k8s-container-image-promoter
  _GOLANGCI_LINT_VERSION: v1.13.2
  _GOPATH: /workspace/go

steps:
- name: "gcr.io/cloud-builders/git"
  id: setup
  entrypoint: "bash"
  args:
  - "-c"
  - "./util/setup.bash"

# We have to use go:debian, not go[:latest], because the latter is based on
# alpine and does not have bash.
- name: "gcr.io/cloud-builders/go:debian"
  id: lint
  waitFor:
  - setup
  entrypoint: "bash"
  env:
  - "GOPATH=${_GOPATH}"
  dir: ${_GOPATH}/src/sigs.k8s.io/${_REPO}
  args:
  - "-c"
  - "./util/lint.bash"

- name: "gcr.io/cloud-builders/bazel"
  id: test
  waitFor:
  - setup
  entrypoint: "bash"
  dir: ${_GOPATH}/src/sigs.k8s.io/${_REPO}
  args:
  - "-c"
  - "./util/test.bash"

- name: "gcr.io/cloud-builders/bazel"
  id: build-image
  dir: ${_GOPATH}/src/sigs.k8s.io/${_REPO}
  args:
  - "build"
  - "--workspace_status_command=$${PWD}/workspace_status.sh"
  - "//:cip-docker-loadable.tar"

- name: "gcr.io/cloud-builders/bazel"
  id: push-image
  entrypoint: "bash"
  dir: ${_GOPATH}/src/sigs.k8s.io/${_REPO}
  args:
  - "-c"
  - "./util/cloudbuild/push-image.bash"
